name: use-env

on:
  workflow_dispatch:

env:
  WORKFLOW_ENV: "workflow_env"

jobs:
  use-env:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      JOB_ENV: "job_env"

    steps:
      - run: echo WORKFLOW_ENV=${{ env.WORKFLOW_ENV }}

      - run: echo JOB_ENV=${{ env.JOB_ENV }}

      - run: echo STEP_ENV=${{ env.STEP_ENV }}
        env:
          STEP_ENV: "step_env"

      - run: echo REPOSITORY_VARIABLES=${{ vars.REPOSITORY_VARIABLES }}

      - run: echo REPOSITORY_SECRETS=${{ secrets.REPOSITORY_SECRETS }}
